# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ebacba42ef18c55c7ed9326c7977eca0c3fb8901e5ac9dcda3b0a5b2dc1504011b34547afbe7ab9543e178f6b497047c20b12b5d2e37e9bccc9b91a94aaaa8f

test:
  secret_key_base: a5c495b6af4b3147be25c51cc867b1fa309f3f050e7095af5323f5662c5999655cbf49eaa2f86ca57c6223233b1fc61bd4c8192f830ac25d99406e0cdb60e978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
